debug: false
server:
  port: 8081
coherence:
  server:
    startup-timeout: 5m
  sessions:
    server:
    - config: coherence-cache-config.xml
logging:
  level:
    Coherence: DEBUG
    com.oracle.coherence: DEBUG
    root: INFO
